# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f760201b1fcaa49490fdf871756ab34896098185049523cef9e2007444586b54b91fcbe9b45f4620092ba9175306bfdeafbaff8f34746a6ac254783c513e2109

test:
  secret_key_base: ca687df27ba3c4997fe4ec3f28902f52dbce1b700756b204ea5479566e57633aae8bf3ad83afbe93e6e9b2bf2ae6f7708686c555abd3c7d7e4c8332656576902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
